name: CI-Main
on:
  push:
    branches: [ main ]

jobs:
  call-workflow-passing-data:
    uses: gforsmo/BI-DevOps/.github/workflows/ci.yml@main
    with:
      workspacename: 'GitHub Action Power BI'
      path: './reports'
    secrets:
      clientid: ${{ secrets.CLIENTID }}
      secret: ${{ secrets.CLIENTSECRET }}
      tenantid: ${{ secrets.TENANTID }}
